# Generated by Django 4.2.7 on 2023-11-11 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_comment', to='home.delivery'),
        ),
        migrations.AlterField(
            model_name='deliverycomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grocerycomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_comment', to='home.grocery'),
        ),
        migrations.AlterField(
            model_name='grocerycomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
